### PR TITLE
Added missing attribute "color" to PlaySessionPlayer.

### PR DESCRIPTION
**Pull request by machnic**

### CODE REVIEW

**Comment by machnic** [comment]
Thanks for merging. Are you planning to continue working on this project?
Do you need help? If yes then I would be more than happy to help you with
it.

2017-10-11 9:54 GMT+02:00 Cosmin Luță <notifications@github.com>:

**Comment by lcosmin** [comment]
Yeah, sorry it took ages for me to merge it. I probably saw the notification, then completely forgot about it until I logged into Github yesterday 😞 

I don't have much time to take care of this project anymore, but I don't want to abandon it either, since a few people are actually using it. I posted on BGG -> Geek Tools yesterday about looking for someone to take over, so if you're interested in helping out, I could add you as a contributor. 

As far as I know there are no major issues, but the library can be improved with small changes like those you've submitted, or by checking/updating the documentation and continuing the rewrite I've started on the `feature/boardgamegeek2` branch (which is functional afaik).

**Comment by machnic** [comment]
No problem, and yes, I'm definitely interested. I'm using this package in one of my small projects I don't want it to be abandoned ;) I will also reply on BGG to create some traffic in your thread. Maybe someone else will be eager to help.

I can start with working on the open issues/features, but for at least some of them I will need your input. As for the rewrite - how much and what exactly is there to be done?

**Comment by lcosmin** [comment]
I'll drop you an email with the details :)

**Comment by machnic** [comment]
👍

**Pull request merged**
