### PR TITLE
Add min/max playing time properties

### PR DESCRIPTION
**Pull request by commadelimited**
This pull request implements min/max play time properties as noted in #26.

### CODE REVIEW

**Comment by commadelimited** [comment]
Hrm. Tests are failing, but I'm not sure why. Happy to look into this, but can you give me a quick tip on how to set up and run your tests locally?

**Comment by lcosmin** [comment]
The tests are failing because they're not up-to-date on the `master` (stable) branch, game data has changed and the test is looking for the outdated one. 

It'd be nice if you could send the pull request for the `develop` branch, that's going to be the new version. I'd like to keep what's on the current `master` as a legacy/unmaintained version after the new one will be finished.

If you want to run the tests locally:

- configure a virtualenv/pyenv
- pip install pytest
- python setup.py develop
- py.test test/test*.py

**Comment by commadelimited** [comment]
Will do!

**Comment by commadelimited** [comment]
Closing this PR In favor of one against the `develop` branch.

**Pull request closed without merging**
