### PR TITLE
Added Call game_list to allow multiple games to be retrieved with one call to the api, added support for the suggested players poll

### PR DESCRIPTION
**Pull request by bar350**

### CODE REVIEW

**Comment by lcosmin** [comment]
Thanks!

**Comment by bar350** [comment]
Do you have any idea when you will release this version to Pypi?

**Comment by lcosmin** [comment]
Not sure, I'm afraid. I simply don't have the time lately to take care of this project, but I haven't given up on it. I'll make an effort and try to release something the next week...

In the mean while, this branch is pretty stable and pip can install directly from github if someone wants to use version 2.

**Comment by bar350** [comment]
if there are any development items I can help with let me know.

**Pull request merged**
