### PR TITLE
Fix issue with infinite recursion on the DictObject used for resources.

### PR DESCRIPTION
**Pull request by tomusher**
Came across this bug when trying to unpickle API objects - the fix prevents getattr from trying to infinitely access the _data attribute.

Should probably write a test for this but not sure how best to do it, any suggestions?

### CODE REVIEW

**Comment by tomusher** [comment]
Sorry just spotted an issue with this, fixing now.

**Comment by lcosmin** [comment]
Nice catch! I added the `__getstate__` and `__setstate__` methods which seem to solve the issue for my test (and I think it's a more elegant fix). Could you please test the `develop` branch to see if the issue occurs anymore?

**Comment by tomusher** [comment]
Great, definitely more elegant but might introduce a bit more complexity - haven't tested it yet but won't this prevent GameObject and other classes that setup other non-```_data``` attributes in ```__init__``` from serialising correctly?

**Comment by lcosmin** [comment]
True, it might. I'm going to try and figure something out tomorrow, otherwise we'll go with your variant.

**Comment by lcosmin** [comment]
Ok, one more try. See if the latest `develop` commit fixes your problem :)

**Comment by tomusher** [comment]
Yeah that seems to have solved it :)

**Comment by lcosmin** [comment]
Ok, released a new version. Thanks! :)

**Pull request closed without merging**
